### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by av-testdrive** [littleant/auto-darkmode-switcher#3]
There either is a component to the script missing or the recent OS updates makes use of it inaccessible. I tried it on 24.10 and 25.04 with the results being the same regardless if gnome-shell-extensions is installed or the gnome-shell reloaded. This wasn't the case about a month ago. Currently, I am on 25.04, here is what I have so far. More can provide more if requested.

![Image](https://github.com/user-attachments/assets/10df8162-df2d-45de-990c-62621732cbf9)
![Image](https://github.com/user-attachments/assets/284a58a0-0b5c-469a-8d23-12e506f217f3)

**Comment by littleant** [comment]
The reason for the installation failure in the second screenshot is the missing gnome-shell-extensions.
After installing the gnome-shell-extensions a user-theme extension should be visible in the first screenshot in the left windows.

Can you confirm, that the user-theme is visible after installing gnome-shell-extensions?

**Comment by av-testdrive** [comment]
> The reason for the installation failure in the second screenshot is the missing gnome-shell-extensions. After installing the gnome-shell-extensions a user-theme extension should be visible in the first screenshot in the left windows.
> 
> Can you confirm, that the user-theme is visible after installing gnome-shell-extensions?

I've installed it before without the app, but can try again and send you the results.

![Image](https://github.com/user-attachments/assets/64c45c82-3242-4a25-b999-6d12024dcbc5)
![Image](https://github.com/user-attachments/assets/5a3a3e8a-013c-407d-9798-0a3c34011cb0)

Still no changes.

**Comment by littleant** [comment]
What's the output of the command `gnome-extensions list`?

Does it include the following line: "user-theme@gnome-shell-extensions.gcampax.github.com"?

**Comment by av-testdrive** [comment]
> What's the output of the command `gnome-extensions list`?
> 
> Does it include the following line: "user-theme@gnome-shell-extensions.gcampax.github.com"?

Yes, among others.

![Image](https://github.com/user-attachments/assets/4d2a95fb-471e-49dd-a74c-096ae5b044f9)

**Comment by littleant** [comment]
Interesting.

Please execute this command and let me know if it returns "0": `gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com' | echo $?`

Also, what does `which grep` return?

**Comment by av-testdrive** [comment]
> Interesting.
> 
> Please execute this command and let me know if it returns "0": `gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com' | echo $?`
> 
> Also, what does `which grep` return?

It does return with a zero and, as for `which grep`, it returns `/usr/bin/grep`.

**Comment by littleant** [comment]
I'm puzzled.

Can you please save the following code to a file (e.g. test.sh), execute it (`bash ./test.sh`) and show me the output:

```
#!/bin/bash

gnome-extensions list > /dev/null
if [[ $? = 0 ]]; then
  echo "Success 1: 'gnome-extensions list' exit-code is $?."
else
  echo "Fail 1: 'gnome-extensions list' exit-code is $?."
fi

gnome-extensions list | grep -q 'NONEXISTENT'
if [[ $? != 0 ]]; then
  echo "Success 2: 'NONEXISTENT' has not been found in extension list."
else
  echo "Fail 2: 'gnome-extensions list | grep -q 'NONEXISTENT'' exit-code is $?."
fi

gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'
if [[ $? = 0 ]]; then
  echo "Success 3: 'user-theme@gnome-shell-extensions.gcampax.github.com' has been found in extension list."
else
  echo "Fail 3: 'gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'' exit-code is $?."
fi

echo "---"

if gnome-extensions list > /dev/null; then
  echo "Success 1: 'gnome-extensions list' exit-code is $?."
else
  echo "Fail 1: 'gnome-extensions list' exit-code is $?."
fi

if ! gnome-extensions list | grep -q 'NONEXISTENT'; then
  echo "Success 2: 'NONEXISTENT' has not been found in extension list."
else
  echo "Fail 2: 'gnome-extensions list | grep -q 'NONEXISTENT'' exit-code is $?."
fi

if gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'; then
  echo "Success 3: 'user-theme@gnome-shell-extensions.gcampax.github.com' has been found in extension list."
else
  echo "Fail 3: 'gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'' exit-code is $?."
fi

echo "---"

if ! gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'; then
  echo "Did not find user-theme."
else
  echo "Found user-theme."
fi

echo "Output of 'gnome-extensions list':"
gnome-extensions list

echo "Output of \"gnome-extensions list | grep 'user-theme@gnome-shell-extensions.gcampax.github.com'\":"
gnome-extensions list | grep 'user-theme@gnome-shell-extensions.gcampax.github.com'
echo "Return code: $?"
```

**Comment by av-testdrive** [comment]
> I'm puzzled.
> 
> Can you please save the following code to a file (e.g. test.sh), execute it (`bash ./test.sh`) and show me the output:
> 
> ```
> #!/bin/bash
> 
> gnome-extensions list > /dev/null
> if [[ $? = 0 ]]; then
>   echo "Success 1: 'gnome-extensions list' exit-code is $?."
> else
>   echo "Fail 1: 'gnome-extensions list' exit-code is $?."
> fi
> 
> gnome-extensions list | grep -q 'NONEXISTENT'
> if [[ $? != 0 ]]; then
>   echo "Success 2: 'NONEXISTENT' has not been found in extension list."
> else
>   echo "Fail 2: 'gnome-extensions list | grep -q 'NONEXISTENT'' exit-code is $?."
> fi
> 
> gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'
> if [[ $? = 0 ]]; then
>   echo "Success 3: 'user-theme@gnome-shell-extensions.gcampax.github.com' has been found in extension list."
> else
>   echo "Fail 3: 'gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'' exit-code is $?."
> fi
> 
> echo "---"
> 
> if gnome-extensions list > /dev/null; then
>   echo "Success 1: 'gnome-extensions list' exit-code is $?."
> else
>   echo "Fail 1: 'gnome-extensions list' exit-code is $?."
> fi
> 
> if ! gnome-extensions list | grep -q 'NONEXISTENT'; then
>   echo "Success 2: 'NONEXISTENT' has not been found in extension list."
> else
>   echo "Fail 2: 'gnome-extensions list | grep -q 'NONEXISTENT'' exit-code is $?."
> fi
> 
> if gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'; then
>   echo "Success 3: 'user-theme@gnome-shell-extensions.gcampax.github.com' has been found in extension list."
> else
>   echo "Fail 3: 'gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'' exit-code is $?."
> fi
> 
> echo "---"
> 
> if ! gnome-extensions list | grep -q 'user-theme@gnome-shell-extensions.gcampax.github.com'; then
>   echo "Did not find user-theme."
> else
>   echo "Found user-theme."
> fi
> 
> echo "Output of 'gnome-extensions list':"
> gnome-extensions list
> 
> echo "Output of \"gnome-extensions list | grep 'user-theme@gnome-shell-extensions.gcampax.github.com'\":"
> gnome-extensions list | grep 'user-theme@gnome-shell-extensions.gcampax.github.com'
> echo "Return code: $?"
> ```

Same here... I'm starting to think its either an update error, bug, or a conflicting app. Here are the results.

![Image](https://github.com/user-attachments/assets/303a39fd-cbac-4569-9263-ea52d1648509)

**Comment by littleant** [comment]
It doesn't make any sense to me right now.

Line 58 fails to detect the user-theme extension in the original script. The same logic in my test-script (line 46) detects the user-theme extension.

If you execute the install-script and still get get the "The user-theme shell-extension needs to be installed. Use 'sudo apt install gnome-shell-extensions' to install it." message, then it must be the elif-syntax. I have no idea what's wrong with it...

**Comment by av-testdrive** [comment]
I even tried a clean install of Oriole (24.XX) and Puffin (25.XX) just to be sure and now the script doesn't work. Again, it was operational with and without the app about a month ago. It could be the latest OS update or something else conflicting with the overall process.

Might there be a way to make it an app sort of like Damask on Flathub/Flatpak? Perhaps it would work.

**Comment by littleant** [comment]
I added the two features GNOME Shell Theme and GNOME Terminal profile a week ago, that's probably why.

You can try to checkout the older version: `git checkout cb3202b`.
That should be the version you are referring to.

It would be interesting what the cause of your issue is, though.

**Comment by av-testdrive** [comment]
> I added the two features GNOME Shell Theme and GNOME Terminal profile a week ago, that's probably why.
> 
> You can try to checkout the older version: `git checkout cb3202b`. That should be the version you are referring to.
> 
> It would be interesting what the cause of your issue is, though.

It worked!

Was there a specific edit in the script at the time or is it a compatibility issue?

![Image](https://github.com/user-attachments/assets/cc6880af-d773-424d-bce6-3190b58f8781)

**Comment by littleant** [comment]
The `gnome-shell-extensions` dependency has been added. It also installs the user-theme extension.
The detection of the user-theme extension is, what is causing your problems.

**Comment by av-testdrive** [comment]
There was an inkling of a feeling that this was the case... I just wasn't sure on which end it was: app, dependencies, or script. I suppose this is solved though not quite?

**Comment by littleant** [comment]
You can use the old version. There's nothing wrong with it.

It's not solved, because I still don't know why your machines fail to detect the user-theme extension.

Just a shot in the dark: Maybe it's a character encoding problem.
Can you execute the following command and tell me the output: `locale charmap`.

**Comment by av-testdrive** [comment]
> You can use the old version. There's nothing wrong with it.
> 
> It's not solved, because I still don't know why your machines fail to detect the user-theme extension.
> 
> Just a shot in the dark: Maybe it's a character encoding problem. Can you execute the following command and tell me the output: `locale charmap`.

It returns UTF-8. I don't mind doing further debugging until something is found. It is odd that even a clean install didn't allow it to run.

**Comment by littleant** [comment]
I tried to reproduce the problem with a fresh install of Ubuntu 25.04.

After installing the gnome-shell-extensions dependency, the install-script tells you to press [Alt]+[F2] and type "r" in the prompt. If I do this, it tells me that restarting is not possible with Wayland.
Did you see this message?

I instead logged out and back in. After that, I could execute the install-script successfully.

Did you try to restart or log out?

**Comment by av-testdrive** [comment]
Yep, I couldn't do the input even when I switched to Xorg from Wayland. I tried the logout, restart, and other solutions found. It seems to differ per user.

**Comment by littleant** [comment]
Is it possible that you share what ISO you download and what options you select when doing a fresh install?

**Comment by av-testdrive** [comment]
> Is it possible that you share what ISO you download and what options you select when doing a fresh install?

https://ubuntu.com/download/desktop

Specifically the Intel/AMD architecture. I'm currently on Puffin.

**Comment by littleant** [comment]
I still cannot reproduce this exact error with that image.

But I fixed a similar error that prevented detection of the user-theme-extension state if the locale was not set to German.

Can you test the latest version please? Just in case it's working now?

**Comment by av-testdrive** [comment]
> I still cannot reproduce this exact error with that image.
> 
> But I fixed a similar error that prevented detection of the user-theme-extension state if the locale was not set to German.
> 
> Can you test the latest version please? Just in case it's working now?

Sure. I can do it on a clean install of either or both if you want. Let me know.

**Comment by littleant** [comment]
Please just test if it is working on your current installation. No need to test it on a clean install for now.

**Comment by av-testdrive** [comment]
It works now.

![Image](https://github.com/user-attachments/assets/16e612a4-e95d-4c2e-b75f-4073e0b0b4ad)

**Comment by littleant** [comment]
Interesting. Could you test a clean install now, too?

Thanks for your time!

**Comment by av-testdrive** [comment]
> Interesting. Could you test a clean install now, too?
> 
> Thanks for your time!

No problem. I was already was in the process of doing it. Sadly, the error returned. I'm on Numbat now.

![Image](https://github.com/user-attachments/assets/29a4e023-096c-4c00-af52-d774988c2e57)
![Image](https://github.com/user-attachments/assets/3aa358bf-bd51-4f78-94d1-a5e3956f2ad3)
![Image](https://github.com/user-attachments/assets/1075ea2a-57a7-4922-a7fa-97459b77a774)

I'll update this post after a restart if it changes anything.

**UPDATE:** Fixed.

![Image](https://github.com/user-attachments/assets/9c7dd1ea-0528-4bde-af74-9ce1a93fe1a8)

**Comment by littleant** [comment]
Thanks for helping find a bug @av-testdrive !

I'm considering this fixed now. In case it comes back, let me know!

**Comment by av-testdrive** [comment]
> Thanks for helping find a bug [@av-testdrive](https://github.com/av-testdrive) !
> 
> I'm considering this fixed now. In case it comes back, let me know!

There is a new issue of it not changing themes with the day cycle. With further digging it seems the installation is not solid. On every reboot it is removed from the `systemctl --user list-timers` so I have to reinstall it again. I wanted to give this a few days of testing to be sure before reopening this again.

**Comment by littleant** [comment]
Please test the newest version, I just fixed this issue (on my machine at least).

**Comment by av-testdrive** [comment]
> Please test the newest version, I just fixed this issue (on my machine at least).

The problem still persists.

**Comment by littleant** [comment]
Just to confirm, you did all of the following:

- pull the newest version from git
- executed install.sh again

And now, when you execute `systemctl --user list-timers` there is no "auto-darkmode-switcher.timer"-unit in the list?

**Comment by av-testdrive** [comment]
Correct. It is removed whenever I restart. It also doesn't change themes after the first time if the computer is left unless done manually.

**Comment by littleant** [comment]
Please show me the output for this command: `systemctl status --user auto-darkmode-switcher`.

**Comment by av-testdrive** [comment]
> Please show me the output for this command: `systemctl status --user auto-darkmode-switcher`.

The first pic is upon a restart that removed the script and the second pic is upon reinstalling it.

![Image](https://github.com/user-attachments/assets/e9d61057-e0df-4c4a-b473-d4b82e12b7d0)

![Image](https://github.com/user-attachments/assets/ae3490d1-65ac-474a-a3a8-d26c8baf2243)

**Comment by littleant** [comment]
Hm, the service displayed as "Loaded" should be from this location: "$HOME/.local/share/systemd/user/", I changed this in the last version, because it doesn't require root permissions when you create it.
Maybe that's the old script that didn't get replaced?

Please try the following:
- `systemctl disable --user auto-darkmode-switcher` to disable the old version.
- `./install.sh` to enable the new version again.
- Show me the output of `systemctl status --user auto-darkmode-switcher` again.

**Comment by av-testdrive** [comment]
> Hm, the service displayed as "Loaded" should be from this location: "$HOME/.local/share/systemd/user/", I changed this in the last version, because it doesn't require root permissions when you create it. Maybe that's the old script that didn't get replaced?
> 
> Please try the following:
> 
> * `systemctl disable --user auto-darkmode-switcher` to disable the old version.
> * `./install.sh` to enable the new version again.
> * Show me the output of `systemctl status --user auto-darkmode-switcher` again.

![Image](https://github.com/user-attachments/assets/f3392c6a-e633-4b60-9664-8acca92ad06e)

![Image](https://github.com/user-attachments/assets/d5dd4e40-4397-423b-b584-753f502d68f5)

**Comment by littleant** [comment]
Don't execute the install script with sudo. It needs to know the current user to install correctly.

Anyhow, please show me the output of `git log -n 1`, so I can confirm you are on the latest commit. I don't have any other idea right now...

**Comment by av-testdrive** [comment]
That was to test something since the `sh ./install.sh` didn't seem to be the issue. I used to do it as just `./install.sh`. Anyways, the return is "fatal: not a git repository (or any of the parent directories): .git".

**Comment by littleant** [comment]
> "fatal: not a git repository (or any of the parent directories): .git".

I guess you didn't clone this repository, so please execute `sha1sum *`. It should output this:

```
415480a4336d0ca4da2803ac1c388b05ec0e0ac2  auto-darkmode-switcher.sh
bc30359f86bed64702102055d0643e0d5a5c3dee  install.sh
439db023483f96b10938e51c6932885058eb79c9  LICENSE
2a3cd5d8592e29a3c241299cc2124a08ad364341  Readme.md
```

**Comment by av-testdrive** [comment]
> > "fatal: not a git repository (or any of the parent directories): .git".
> 
> I guess you didn't clone this repository, so please execute `sha1sum *`. It should output this:
> 
> ```
> 415480a4336d0ca4da2803ac1c388b05ec0e0ac2  auto-darkmode-switcher.sh
> bc30359f86bed64702102055d0643e0d5a5c3dee  install.sh
> 439db023483f96b10938e51c6932885058eb79c9  LICENSE
> 2a3cd5d8592e29a3c241299cc2124a08ad364341  Readme.md
> ```

It returns 3/4 of the same lines. The first is different.
```
36b399e32cde798e0b1938493859cf15ffae3ec2  auto-darkmode-switcher.sh
bc30359f86bed64702102055d0643e0d5a5c3dee  install.sh
439db023483f96b10938e51c6932885058eb79c9  LICENSE
2a3cd5d8592e29a3c241299cc2124a08ad364341  Readme.md
```
Odd, I did download and installed the latest update. Is there a way to fully remove the install?

**Comment by littleant** [comment]
You probably modified the auto-darkmode-switcher.sh file with your own latitude and longitude. So it should be ok.
I'm currently out of ideas.

**Comment by littleant** [comment]
Ok, lets try to remove the old service from your system, in case that's the problem:

1. Do a `sudo rm /etc/systemd/user/auto-darkmode-switcher.service` to delete the old service file.
2. Run `systemctl disable --now --user auto-darkmode-switcher` and `systemctl daemon-reload` to be extra sure it's disabled, stopped and removed.
3. Reboot. Maybe it helps to reset something.
4. Run `./install.sh` again, to enable the new service file.

(The new service file is located at "${HOME}/.local/share/systemd/user/auto-darkmode-switcher.service".)

Reasoning:
The old service file ran too early after log-in to detect the user-theme-extension.
The new service file runs after the gnome-session is ready, which solved this error on my PC. So either your PC executes the old service-file, or my fix doesn't work on your PC.

**Comment by av-testdrive** [comment]
> Ok, lets try to remove the old service from your system, in case that's the problem:
> 
>     1. Do a `sudo rm /etc/systemd/user/auto-darkmode-switcher.service` to delete the old service file.
> 
>     2. Run `systemctl disable --now --user auto-darkmode-switcher` and `systemctl daemon-reload` to be extra sure it's disabled, stopped and removed.
> 
>     3. Reboot. Maybe it helps to reset something.
> 
>     4. Run `./install.sh` again, to enable the new service file.
> 
> 
> (The new service file is located at "${HOME}/.local/share/systemd/user/auto-darkmode-switcher.service".)
> 
> Reasoning: The old service file ran too early after log-in to detect the user-theme-extension. The new service file runs after the gnome-session is ready, which solved this error on my PC. So either your PC executes the old service-file, or my fix doesn't work on your PC.

Alright, now it sticks! 😄 Thank you.

**Comment by av-testdrive** [comment]
Minor update: The problem still persist usually when the computer wakes up from sleep sleep and/or suspension. The file keeps getting deleted from the folders its downloaded to.

**Comment by littleant** [comment]
> The file keeps getting deleted from the folders its downloaded to.

What file are you referring to?

**Comment by av-testdrive** [comment]
The `auto-darkmode-switcher.timer` and `auto-darkmode-switcher.service`. They both somehow get deleted when the computer either wakes from sleep or suspend after the second theme change.

**Comment by littleant** [comment]
Strange.

Can you post the output of `systemctl status --user auto-darkmode-switcher` and `systemctl status --user auto-darkmode-switcher.timer` the next time the files are being deleted?

Thanks!

**Comment by av-testdrive** [comment]
> Strange.
> 
> Can you post the output of `systemctl status --user auto-darkmode-switcher` and `systemctl status --user auto-darkmode-switcher.timer` the next time the files are being deleted?
> 
> Thanks!

Update: Last night I did a thorough clean install that seems to be working properly now, but I said the same thing a while ago... This morning it correctly changed themes from night/dark to day/light after waking from suspend so you'll be see its outputs.

Here is both returns:

![Image](https://github.com/user-attachments/assets/64941573-a221-4f1d-8e7a-762112872d6b)

**Comment by littleant** [comment]
The screenshot looks good. Please let me know what the output is, should it happen again.
